// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB69yn-hnroJiA4hZz3FaPAaP_ABn7NLT0',
    appId: '1:816252258870:web:582e3d4e61f496a334a697',
    messagingSenderId: '816252258870',
    projectId: 'homework4-12e64',
    authDomain: 'homework4-12e64.firebaseapp.com',
    storageBucket: 'homework4-12e64.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDifympeHmMdFpIvVe0PzsPnxSOpDxSL7w',
    appId: '1:816252258870:android:2720aa392912508534a697',
    messagingSenderId: '816252258870',
    projectId: 'homework4-12e64',
    storageBucket: 'homework4-12e64.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoSVa0HW1lAidF-w6feKkNr3Q4trX0DCs',
    appId: '1:816252258870:ios:e57f4406f48d483434a697',
    messagingSenderId: '816252258870',
    projectId: 'homework4-12e64',
    storageBucket: 'homework4-12e64.firebasestorage.app',
    iosBundleId: 'com.example.homework4',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDoSVa0HW1lAidF-w6feKkNr3Q4trX0DCs',
    appId: '1:816252258870:ios:e57f4406f48d483434a697',
    messagingSenderId: '816252258870',
    projectId: 'homework4-12e64',
    storageBucket: 'homework4-12e64.firebasestorage.app',
    iosBundleId: 'com.example.homework4',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB69yn-hnroJiA4hZz3FaPAaP_ABn7NLT0',
    appId: '1:816252258870:web:f37f26e15144fc1034a697',
    messagingSenderId: '816252258870',
    projectId: 'homework4-12e64',
    authDomain: 'homework4-12e64.firebaseapp.com',
    storageBucket: 'homework4-12e64.firebasestorage.app',
  );
}
